### ISSUE TITLE
Activate GitHub Pages for this repository?

### ISSUE THREAD

**Issue by kjmitch** [WyoARCC/slurm-dash#2]
Setting up the repo to use GitHub Pages would allow the project result to be viewed (and debugged) from GitHub; do we want to do this? The data is anonymized, and a quick way to check out the current state of the dashboard could be useful, but I realized we might not want it published here since it's easy enough to run a web server with a local copy of the repo, and the final version will go up elsewhere.

If we do want to set this up, I don't seem to have access to the settings for the repo.

**Comment by larskotthoff** [comment]
I think that's a good idea. People would still have to find it, so I don't think the risk is very high. And of course the data is public anyway.

**Comment by jbaksta** [comment]
Available through the /docs directory in the repo so pages should be available. While it's not really /docs, I think it should work for this case.

**Comment by jbaksta** [comment]
I should have asked, do you want it on the master branch?
